server:
  port: 8200
  
management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true  
  
spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/testdb?useSSL=false
#    username: naveen
    password: database
    url: jdbc:mysql://mysql-learn/testdb?useSSL=false&allowPublicKeyRetrieval=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect